version: '3'

services:

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    volumes:
      - "${HOME}/.m2:/root/.m2"
    networks:
      - backend
    container_name: discovery-service

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - "${HOME}/.m2:/root/.m2"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/account_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      - mysql-db
      - discovery-service
    networks:
      - backend
      - accounts
    container_name: account-service


  mysql-db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: account_service
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - accounts
    container_name: db-account-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
      - "8760:8760"
    volumes:
      - "${HOME}/.m2:/root/.m2"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
    networks:
      - backend
    container_name: api-gateway

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    ports:
      - "5858:5858"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
    volumes:
      - "${HOME}/storage-files:/app/files"
      - "${HOME}/.m2:/root/.m2"
    networks:
      - backend
    container_name: storage-service

  offers-service:
    build:
      context: ./offers-service
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
      - "7800:7800"
    volumes:
      - "${HOME}/.m2:/root/.m2"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://offers-db:3306/offers_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      - offers-db
      - discovery-service
    networks:
      - backend
      - offers
    container_name: offers-service


  offers-db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: offers_service
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - offers
    container_name: db-offers-service


networks:
  backend:
  offers:
  accounts:
