version: '3'

services:

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/account_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysql-db
    networks:
      - backend
    container_name: account-service


  mysql-db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: account_service
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - backend
    container_name: db-account-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8762:8080"
    networks:
      - backend
    container_name: api-gateway

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8080"
    networks:
      - backend
    container_name: discovery-service


networks:
  backend: