spring:
  application:
    name: api-gateway
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    accounts:
      path: /accounts/**
      url: http://account-service:8080/accounts/
      sensitive-headers: Cookie,Set-Cookie
