spring:
  application:
    name: api-gateway
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Origin
  routes:
    accounts:
      path: /accounts/**
      url: http://account-service:8080/accounts/
    oauth:
      path: /oauth/**
      url: http://account-service:8080/oauth
    storage:
      path: /downloadFile/**
      url: http://storage-service:5858/downloadFile
    games:
      path: /**
      url: http://offers-service:7878
    email:
      path: /**
      url: http://email-service:9898
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.security: DEBUG

