spring:
  application:
    name: storage-servie
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 5858
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
